name = "HetDister"
uuid = "50651ce3-0423-45d2-b99c-8ea4267d2717"
version = "0.10.7"
authors = ["Tommaso Stentella <stentell@molgen.mpg.de> and contributors"]

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DynamicPPL = "366bfd00-2699-11ea-058f-f148b4cae6d8"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
HistogramBinnings = "8296b526-8b84-45d3-81d6-36727ca56808"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MvNormalCDF = "37188c8d-bc69-4638-b057-733e744175ec"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PreallocationTools = "d236fae5-4411-538c-8e31-a6e3d9e00b46"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[compat]
Accessors = "0.1.42"
Distributions = "0.25.120"
DynamicPPL = "0.36.12, 0.37, 0.38, 0.39"
FastGaussQuadrature = "1.1.0"
ForwardDiff = "1.0.1"
HistogramBinnings = "0.1.1"
LinearAlgebra = "1.10, 1.11.0"
Logging = "1.10, 1.11.0"
MvNormalCDF = "0.3.2"
Optim = "1.13.2"
PreallocationTools = "0.4.34, 1"
Printf = "1.10, 1.11.0"
Random = "1.10, 1.11.0"
Statistics = "1.10, 1.11.1"
StatsAPI = "1.7.1"
StatsBase = "0.34.5"
Turing = "0.42"
julia = "1.12"
