name = "DemoInfer"
uuid = "50651ce3-0423-45d2-b99c-8ea4267d2717"
authors = ["Tommaso Stentella <stentell@molgen.mpg.de> and contributors"]
version = "0.4.1"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DynamicPPL = "366bfd00-2699-11ea-058f-f148b4cae6d8"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
HistogramBinnings = "8296b526-8b84-45d3-81d6-36727ca56808"
KissSmoothing = "23b0397c-cd08-4270-956a-157331f0528f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MLDs = "cac4bed1-6c8c-4dbe-be0d-c63a427c1233"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PopSimIBX = "88d7705d-7f72-40d5-8927-d9bc8cbe062a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[compat]
Accessors = "0.1.38"
Distributions = "0.25.112"
DynamicPPL = "0.30.2, 0.31, 0.34, 0.35, 0.36"
ForwardDiff = "0.10.37, 1"
HistogramBinnings = "0.1"
KissSmoothing = "1.0.8"
LinearAlgebra = "1.10.7 - 1.11.0, 1"
Logging = "1.10.7 - 1.11.0, 1"
MLDs = "0.1.0"
Optim = "1.9.4"
PopSimIBX = "0.2.2 - 0.4.0"
Printf = "1.10.7 - 1.11.0, 1"
Statistics = "1.10.7 - 1.11.0, 1"
StatsAPI = "1.7.0"
StatsBase = "0.34.3"
Turing = "0.35.1, 0.36, 0.37, 0.38"
julia = "1.10"
